version: "3.9"

services:
  app:
    container_name: app
    build:
      context: ./server
    depends_on:
      - db
    ports:
      - 3000:3000

  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    # volumes:
    #   - ./data:/var/lib/postgresql/data
